package de.choong.model.anime;

public enum Genre {
    ACTION, //
    ADVENTURE, //
    CARS, //
    COMEDY, //
    DEMENTIA, //
    DEMONS, //
    DRAMA, //
    ECCHI, //
    FANTASY, //
    GAME, //
    HAREM, //
    HENTAI, //
    HISTORICAL, //
    HORROR, //
    JOSEI, //
    KIDS, //
    MAGIC, //
    MARTIAL_ARTS, //
    MECHA, //
    MILITARY, //
    MUSIC, //
    MYSTERY, //
    PARODY, //
    POLICE, //
    PSYCHOLOGICAL, //
    ROMANCE, //
    SAMURAI, //
    SCHOOL, //
    SCIFI, //
    SEINEN, //
    SHOUJO, //
    SHOUJOAI, //
    SHOUNEN, //
    SHOUNENAI, //
    SLICEOFLIFE, //
    SPACE, //
    SPORTS, //
    SUPERPOWER, //
    SUPERNATURAL, //
    THRILLER, //
    YAOI, //
    YURI, //
}
